// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW8KHPtUscZJp1RvsMmUkiDLKW-GJ7lFk',
    appId: '1:34126480760:web:bd37d0ce900ebea431748d',
    messagingSenderId: '34126480760',
    projectId: 'book-592f2',
    authDomain: 'book-592f2.firebaseapp.com',
    storageBucket: 'book-592f2.appspot.com',
    measurementId: 'G-DMHL7XYDSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUDuBm-QZsR3CYNQrry5la7RDCmMfqsUo',
    appId: '1:34126480760:android:31edb3e46baeb87231748d',
    messagingSenderId: '34126480760',
    projectId: 'book-592f2',
    storageBucket: 'book-592f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiVYnC8APje-cochvT0wXn1c4QZsTx5Xs',
    appId: '1:34126480760:ios:4cae3b6d1b32385b31748d',
    messagingSenderId: '34126480760',
    projectId: 'book-592f2',
    storageBucket: 'book-592f2.appspot.com',
    iosClientId: '34126480760-93nrnhpkk25fjp7gtv93db380ii4grp0.apps.googleusercontent.com',
    iosBundleId: 'com.dytech.book',
  );
}
